name: Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  configs_check:
    name: Validate configs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Run ESLint
        run: yarn eslint .

      - name: Validate marketplace config schema
        run: './tools/marketplace-config-validator/script.sh'

      - name: Validate featured networks config schema
        run: './tools/featured-networks-config-validator/script.sh'

      - name: Validate footer links config schema
        run: './tools/footer-links-config-validator/script.sh'
